### ISSUE TITLE
Multiple multipart files not detected as binary

### ISSUE THREAD

**Issue by lselden** [readmeio/oas-to-har#7]
According to the [OpenAPI 3.0 Spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#considerations-for-file-uploads) *(found via the [Swagger](https://swagger.io/docs/specification/describing-request-body/file-upload/#multiple))* You can include an array of files into a multipart request:

```yaml
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
```

However, this library only looks for properties with the `format: binary` and ignores `type: array`, so they end up just looking like strings

[Relevant code](https://github.com/readmeio/oas-to-har/blob/main/src/index.js#L280)

**Comment by erunion** [comment]
Better late than never but this is now resolved in https://github.com/readmeio/oas-to-har/pull/109, [fetch-har@8.1.0](https://github.com/readmeio/fetch-har/releases/tag/8.1.0) and will be released to ReadMe sites later this week.
