### ISSUE TITLE
multipart - JSON properties result in "[object Object]"

### ISSUE THREAD

**Issue by lselden** [readmeio/oas-to-har#8]
One possibility with `multipart/form-data` requests is to include a JSON payload alongside other data (like JSON metadata along with an attached binary file). The OpenAPI 3.0 spec [lays out rules](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#special-considerations-for-multipart-content) `type: object` on how to parse `multipart` parameters and set their `Content-Type`, including looking at the `encoding` attribute.

This library just [converts data to a String](https://github.com/readmeio/oas-to-har/blob/main/src/index.js#L299), which means any properties with `type: object` get rendered as `[object Object]` instead of using `JSON.stringify` to create an accurate representation.

Unfortunately this breaks being able to specify the shape of `multipart` JSON payloads on readme.com

**Comment by erunion** [comment]
This should be resolved now with https://github.com/readmeio/oas-to-har/pull/30
